### ISSUE TITLE
Add keyframe-selector-notation

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint-config-standard#255]
Shall we add with "percentage" option?

**Comment by ybiquitous** [comment]
I'm not sure if there is a *common* convention. 🤔 

IMO, I prefer only percentages over a mix of keywords and percentages, e.g.

```css
/* 👎🏼 */
@keyframes foo {
  from { opacity: 0; }
  50% { opacity: 0.5; }
  to { opacity: 1; }
}

/* 👍🏼 */
@keyframes foo {
  0% { opacity: 0; }
  50% { opacity: 0.5; }
  100% { opacity: 1; }
}
```

But I always don't want consistency, especially in simple cases, e.g.

```css
/* 👍🏼 */
@keyframes foo {
  from { opacity: 0; }
  to { opacity: 1; }
}

/* 👍🏼 also */
@keyframes foo {
  0% { opacity: 0; }
  100% { opacity: 1; }
}

/* 👍🏼 also */
@keyframes foo {
  to { opacity: 1; }
}
```

In an example of [this article](https://css-tricks.com/snippets/css/keyframe-animation-syntax/), percentages and keywords are used naturally.

The `"percentage"` option seems valuable for consistency in the following case:

```css
@keyframes foo {
  from { opacity: 0; }
  50% { opacity: 0.5; }
  to { opacity: 1; }
}
```

But people may feel noisy in the following case of mixing both:

```css
@keyframes foo {
  0% { opacity: 0; }
  50% { opacity: 0.5; }
  100% { opacity: 1; }
}

@keyframes bar {
  from { opacity: 0; } /* => Expected "from" to be "0%" */
  to { opacity: 1; }   /* => Expected "to" to be "100%" */
}
```

What do you think?

**Comment by jeddy3** [comment]
> percentages and keywords are used naturally.
> But people may feel noisy in the following case of mixing both:

I think you're right.

Only the following feels unnatural:

```css
@keyframes foo {
  from { opacity: 0; }
  50% { opacity: 0.5; }
  to { opacity: 1; }
}
```

Let's add an (`ignore`) option to the rule to enforce only this and use the option in this config. People can, if they want, make the rule stricter in their own configs by not using the option.
