### ISSUE TITLE
Upgrade to 32.0.0 causes parseError with media query in .less file

### ISSUE THREAD

**Issue by PinkChampagne17** [stylelint/stylelint-config-standard#287]
### What steps are needed to reproduce the bug?

1. Upgrade the `stylelint-config-standard` package from version `31.0.0` to `32.0.0`.
2. Type the following code block in `test.less` file:
```less
div {
  @print : ~'print';
  @media @print {
    color: black;
  }
}
```
3. Run `stylelint test.less`.

### What did you expect to happen?

Before upgrading the stylelint-config-standard package to 32.0.0, stylelint will not throw an error when using the given code block in a .less file.

### What actually happened?

```
test.less
 4:10  ✖  Cannot parse media query  parseError

1 problem (1 error, 0 warnings)
```
