### ISSUE TITLE
Consider add the rule 'property-no-unknown'

### ISSUE THREAD

**Issue by cristianurbano** [stylelint/stylelint-config-standard#33]
It would be good to add the ["property-no-unknown": true](http://stylelint.io/user-guide/rules/property-no-unknown/) , in order to check properties defined in the CSS Specifications and browser specific properties to be known. I think this rule is basic. 

Now without that rule you will not have errors with the following css:
```css
.myClass {
   colr: #fff;
   bakgroun: #fff;
   pepe: #fff;
}
```
What do you think?
